# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03c9a5fd77efdb8f099e4c8bc4508ab87c36b82f8c5c95814914928e2913c334942b176597a554b04a644f84a54d5c2af46afd3fa5ab7b98c57990d7bc05bf0b

test:
  secret_key_base: 9ef7e445e7d4bd79b750c748d4c77862bfc65b81096a6b63c9ef435a27af07420017e7b597ffa1a9bcd1cad9f2b7d017cc62d73d0746905b700e441da64c5211

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
